site_name: 'Production Management'

theme: readthedocs

docs_dir: 'docs'

pages:
- ['index.md', 'Installation']
- ['getting-started.md', 'Run the Application']
- ['machine.md', 'Machine']
- ['color.md', 'Color']
- ['product.md', 'Product']
- ['shift.md', 'Shift']
- ['role.md', 'Role']
- ['user.md', 'User']
- ['team.md', 'Team (Schedule)']
- ['order.md', 'Order and Production Entry']
- ['history.md', 'History for Reporting']
- ['dashboard.md', 'Dashboard']
- ['export.md', 'Data Export']
- ['db.md', 'Database Backup']





