site_name: 'Production Management'

theme: readthedocs

docs_dir: 'docs'

pages:
- ['index.md', 'Installation']
- ['getting-started.md', 'Run the Application']
- ['machine.md', 'Machine Setup']
- ['product.md', 'Product Setup']
- ['shift.md', 'Shift Setup']
- ['user.md', 'User Setup']
- ['team.md', 'Team (Schedule) Setup']
- ['order.md', 'Order and Production Entry']
- ['history.md', 'History for Reporting']
- ['dashboard.md', 'Dashboard']
- ['db.md', 'Database Backup']





